config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  # public routes
  resources :exercises do
    collection do
      get 'filter'
    end
  end
  resources :routines
  resources :blocks
  # private routes
  resources :aspects
  devise_for :users
  resources :movement_patterns
  resources :muscles
  resources :muscle_groups
  resources :tools do
    collection do
      get 'list'
    end
  end
  resources :protocols
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/aspect.rb
class Aspect < ApplicationRecord
  has_many :blocks, dependent: :restrict_with_error
  validates :name, uniqueness: true, presence: true
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :user
  belongs_to :protocol
  belongs_to :aspect
  has_many :exercises
  has_many :block_exercises, dependent: :destroy
  has_many :exercises, through: :block_exercises
  has_many :block_inner_blocks, dependent: :destroy
  has_many :inner_blocks, through: :block_inner_blocks, source: :inner_block
  validates :name, uniqueness: { scope: :user_id }
end

app/models/block_exercise.rb
class BlockExercise < ApplicationRecord
  belongs_to :block
  belongs_to :exercise
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :user
  has_many :exercise_muscles, dependent: :destroy
  has_many :muscles, through: :exercise_muscles
  has_many :exercise_movement_patterns, dependent: :destroy
  has_many :movement_patterns, through: :exercise_movement_patterns
  has_many :exercise_variants, dependent: :destroy
  has_many :variants, through: :exercise_variants, source: :variant
  has_many :reverse_exercise_variants, foreign_key: :variant_id, class_name: 'ExerciseVariant', dependent: :destroy
  has_many :variant_ofs, through: :reverse_exercise_variants, source: :exercise
  has_many :exercise_tools, dependent: :destroy
  has_many :tools, through: :exercise_tools
  has_many :block_exercises, dependent: :destroy
  has_many :blocks, through: :block_exercises
  validates :name, uniqueness: { scope: :user_id }, presence: true
end

app/models/exercise_muscle.rb
class ExerciseMuscle < ApplicationRecord
  belongs_to :exercise
  belongs_to :muscle
  validates :muscle_id, uniqueness: { scope: :exercise_id }
end

app/models/exercise_tool.rb
class ExerciseTool < ApplicationRecord
  belongs_to :exercise
  belongs_to :tool
  validates :tool_id, uniqueness: { scope: :exercise_id }
end

app/models/exercise_variant.rb
class ExerciseVariant < ApplicationRecord
  belongs_to :exercise
  belongs_to :variant, class_name: 'Exercise', foreign_key: 'variant_id'
  validates :variant_id, uniqueness: { scope: :exercise_id }
end

app/models/movement_pattern.rb
class MovementPattern < ApplicationRecord
  has_many :exercise_movement_patterns, dependent: :destroy
  has_many :exercises, through: :exercise_movement_patterns
  validates :name, uniqueness: true, presence: true
end

app/models/muscle.rb
class Muscle < ApplicationRecord
  belongs_to :muscle_group
  has_many :exercise_muscles, dependent: :destroy
  has_many :exercises, through: :exercise_muscles
  validates :name, uniqueness: true, presence: true
  validates :muscle_group_id, presence: true
end

app/models/muscle_group.rb
class MuscleGroup < ApplicationRecord
  has_many :muscles, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/protocol.rb
class Protocol < ApplicationRecord
  MEASURE_OPTIONS = { time: 0, sets: 1 }.freeze
  enum :measure_unit, MEASURE_OPTIONS, validate: true
  has_many :blocks, dependent: :restrict_with_exception
  validates :name, uniqueness: true, presence: true
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :user
end

app/models/routine_block.rb
class RoutineBlock < ApplicationRecord
  belongs_to :routine
  belongs_to :block
end

app/models/tool.rb
class Tool < ApplicationRecord
  has_many :exercise_tools, dependent: :destroy
  has_many :exercises, through: :exercise_tools
  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :exercises
end

app/controllers/aspects_controller.rb
class AspectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_aspect, only: %i[show edit update destroy]

  # GET /aspects or /aspects.json
  def index
    @aspects = Aspect.all
  end

  # GET /aspects/1 or /aspects/1.json
  def show
  end

  # GET /aspects/new
  def new
    @aspect = Aspect.new
  end

  # GET /aspects/1/edit
  def edit
  end

  # POST /aspects or /aspects.json
  def create
    @aspect = Aspect.new(aspect_params)

    respond_to do |format|
      if @aspect.save
        format.html { redirect_to aspect_url(@aspect), notice: "Aspect was successfully created." }
        format.json { render :show, status: :created, location: @aspect }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aspect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aspects/1 or /aspects/1.json
  def update
    respond_to do |format|
      if @aspect.update(aspect_params)
        format.html { redirect_to aspect_url(@aspect), notice: "Aspect was successfully updated." }
        format.json { render :show, status: :ok, location: @aspect }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aspect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aspects/1 or /aspects/1.json
  def destroy
    @aspect.destroy!

    respond_to do |format|
      format.html { redirect_to aspects_url, notice: "Aspect was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_aspect
    @aspect = Aspect.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def aspect_params
    params.require(:aspect).permit(:name, :description)
  end
end

app/helpers/aspects_helper.rb
module AspectsHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/muscles_helper.rb
module MusclesHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
  def sort_link(column:, label:)
    if column == params[:column]
      link_to(label, list_tools_path(column:, direction: next_direction))
    else
      link_to(label, list_tools_path(column:, direction: 'asc'))
    end
  end

  def next_direction
    params[:direction] == 'asc' ? 'desc' : 'asc'
  end
end

app/views/aspects/_aspect.html.erb
<% if action_name != "show" %>
  <tr class="table-row">
    <td class="table-cell text-center border border-gray-400">
      <%= aspect.name %>
    </td>
    <td class="table-cell text-center border border-gray-400">
      <%= aspect.description %>
    </td>
    <td class="table-cell text-center border border-gray-400">
      <%= aspect.blocks.length %>
    </td>
    <td class="table-cell text-center border border-gray-400">
      <div class="flex flex-row items-center justify-evenly">
        <%= link_to aspect, {"data-turbo-frame": "_top"} do %>
          <%= render 'shared/view_icon' %>
        <% end %>
        <%= link_to edit_aspect_path(aspect), {class: "border-1 border-solid rounded-sm", "data-turbo-frame": "_top"} do %>
          <%= render 'shared/edit_icon' %>
        <% end %>
        <hr class="mt-6">
      </div>
    </td>
  </tr>
<% end %>
<% if action_name == "show" %>
  <div id="<%= dom_id aspect %>" class="border-solid rounded-md border-2 p-2 m-1">
    <p class="my-5">
      <strong class="block font-medium mb-1">Name:</strong>
      <%= aspect.name %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Description:</strong>
      <%= aspect.description %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1"># blocks:</strong>
      <%= aspect.blocks.length %>
    </p>

    <% if action_name != "show" %>
      <%= link_to "Show this aspect", aspect, {class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"} %>
      <%= link_to "Edit this aspect", edit_aspect_path(aspect), {class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"} %>
      <hr class="mt-6">
    <% end %>
  </div>
<% end %>

app/views/aspects/_aspects.html.erb
<% if action_name != "show" %>
<turbo-frame id="aspects">
  <table class="table table-fixed w-full border border-gray-400">
    <thead class="table-header-group">
      <tr class="table-row">
        <th class="table-cell text-center px-4 py-2 text-emerald-600 border border-gray-400">
          Name
        </th>
        <th class="table-cell text-center px-4 py-2 text-emerald-600 border border-gray-400">Description</th>
        <th class="table-cell text-center px-4 py-2 text-emerald-600 border border-gray-400"># Blocks</th>
        <th class="table-cell text-center px-4 py-2 text-emerald-600 border border-gray-400">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% aspects.each do |aspect| %>
          <%= render aspect %>
      <% end %>
    </tbody>
  </table>
</turbo-frame>
<% end %>
<% if action_name == "show" %>
  <%= render aspect%>
<% end %>

app/views/aspects/_form.html.erb
<%= form_with(model: aspect, class: "contents") do |form| %>
  <% if aspect.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(aspect.errors.count, "error") %> prohibited this aspect from being saved:</h2>

      <ul>
        <% aspect.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/aspects/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing aspect</h1>

  <%= render "form", aspect: @aspect %>

  <%= link_to "Show this aspect", @aspect, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to aspects", aspects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/aspects/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Aspects</h1>
    <%= link_to "New aspect", new_aspect_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div class="my-2">
    <%= render "aspects", aspects: @aspects %>
  </div>
</div>

app/views/aspects/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New aspect</h1>

  <%= render "form", aspect: @aspect %>

  <%= link_to "Back to aspects", aspects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/aspects/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @aspect %>

    <%= link_to "Edit this aspect", edit_aspect_path(@aspect), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this aspect", aspect_path(@aspect), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to aspects", aspects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>