config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  # public routes
  resources :exercises do
    collection do
      get 'filter'
    end
  end
  resources :routines
  resources :blocks
  # private routes
  resources :aspects
  devise_for :users
  resources :movement_patterns
  resources :muscles
  resources :muscle_groups
  resources :tools do
    collection do
      get 'list'
    end
  end
  resources :protocols
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/aspect.rb
class Aspect < ApplicationRecord
  has_many :blocks, dependent: :restrict_with_error
  validates :name, uniqueness: true, presence: true
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :user
  belongs_to :protocol
  belongs_to :aspect
  has_many :exercises
  has_many :block_exercises, dependent: :destroy
  has_many :exercises, through: :block_exercises
  has_many :block_inner_blocks, dependent: :destroy
  has_many :inner_blocks, through: :block_inner_blocks, source: :inner_block
  validates :name, uniqueness: { scope: :user_id }
end

app/models/block_exercise.rb
class BlockExercise < ApplicationRecord
  belongs_to :block
  belongs_to :exercise
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :user
  has_many :exercise_muscles, dependent: :destroy
  has_many :muscles, through: :exercise_muscles
  has_many :exercise_movement_patterns, dependent: :destroy
  has_many :movement_patterns, through: :exercise_movement_patterns
  has_many :exercise_variants, dependent: :destroy
  has_many :variants, through: :exercise_variants, source: :variant
  has_many :reverse_exercise_variants, foreign_key: :variant_id, class_name: 'ExerciseVariant', dependent: :destroy
  has_many :variant_ofs, through: :reverse_exercise_variants, source: :exercise
  has_many :exercise_tools, dependent: :destroy
  has_many :tools, through: :exercise_tools
  has_many :block_exercises, dependent: :destroy
  has_many :blocks, through: :block_exercises
  validates :name, uniqueness: { scope: :user_id }, presence: true
end

app/models/exercise_muscle.rb
class ExerciseMuscle < ApplicationRecord
  belongs_to :exercise
  belongs_to :muscle
  validates :muscle_id, uniqueness: { scope: :exercise_id }
end

app/models/exercise_tool.rb
class ExerciseTool < ApplicationRecord
  belongs_to :exercise
  belongs_to :tool
  validates :tool_id, uniqueness: { scope: :exercise_id }
end

app/models/exercise_variant.rb
class ExerciseVariant < ApplicationRecord
  belongs_to :exercise
  belongs_to :variant, class_name: 'Exercise', foreign_key: 'variant_id'
  validates :variant_id, uniqueness: { scope: :exercise_id }
end

app/models/movement_pattern.rb
class MovementPattern < ApplicationRecord
  has_many :exercise_movement_patterns, dependent: :destroy
  has_many :exercises, through: :exercise_movement_patterns
  validates :name, uniqueness: true, presence: true
end

app/models/muscle.rb
class Muscle < ApplicationRecord
  belongs_to :muscle_group
  has_many :exercise_muscles, dependent: :destroy
  has_many :exercises, through: :exercise_muscles
  validates :name, uniqueness: true, presence: true
  validates :muscle_group_id, presence: true
end

app/models/muscle_group.rb
class MuscleGroup < ApplicationRecord
  has_many :muscles, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/protocol.rb
class Protocol < ApplicationRecord
  MEASURE_OPTIONS = { time: 0, sets: 1 }.freeze
  enum :measure_unit, MEASURE_OPTIONS, validate: true
  has_many :blocks, dependent: :restrict_with_exception
  validates :name, uniqueness: true, presence: true
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :user
end

app/models/routine_block.rb
class RoutineBlock < ApplicationRecord
  belongs_to :routine
  belongs_to :block
end

app/models/tool.rb
class Tool < ApplicationRecord
  has_many :exercise_tools, dependent: :destroy
  has_many :exercises, through: :exercise_tools
  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :exercises
end

app/controllers/muscles_controller.rb
class MusclesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_muscle, only: %i[show edit update destroy]
  before_action :set_select_collections, only: %i[edit update new create]

  # GET /muscles or /muscles.json
  def index
    @muscles = Muscle.all.includes(:muscle_group, :exercises)
  end

  # GET /muscles/1 or /muscles/1.json
  def show
    @muscle = Muscle.includes(:muscle_group, :exercises).find(params[:id])
  end

  # GET /muscles/new
  def new
    @muscle = Muscle.new
    @muscle_groups = MuscleGroup.order(:name)
  end

  # GET /muscles/1/edit
  def edit
    @muscle_groups = MuscleGroup.order(:name)
  end

  # POST /muscles or /muscles.json
  def create
    @muscle = Muscle.new(muscle_params)

    respond_to do |format|
      if @muscle.save
        format.html { redirect_to muscle_url(@muscle), notice: 'Muscle was successfully created.' }
        format.json { render :show, status: :created, location: @muscle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @muscle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /muscles/1 or /muscles/1.json
  def update
    respond_to do |format|
      if @muscle.update(muscle_params)
        format.html { redirect_to muscle_url(@muscle), notice: 'Muscle was successfully updated.' }
        format.json { render :show, status: :ok, location: @muscle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @muscle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /muscles/1 or /muscles/1.json
  def destroy
    @muscle.destroy!

    respond_to do |format|
      format.html { redirect_to muscles_url, notice: 'Muscle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_muscle
    @muscle = Muscle.find(params[:id])
  end

  def set_select_collections
    @muscle_groups = MuscleGroup.all
  end

  # Only allow a list of trusted parameters through.
  def muscle_params
    params.require(:muscle).permit(:name, :description, :muscle_group_id)
  end
end

app/helpers/aspects_helper.rb
module AspectsHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/muscles_helper.rb
module MusclesHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
  def sort_link(column:, label:)
    if column == params[:column]
      link_to(label, list_tools_path(column:, direction: next_direction))
    else
      link_to(label, list_tools_path(column:, direction: 'asc'))
    end
  end

  def next_direction
    params[:direction] == 'asc' ? 'desc' : 'asc'
  end
end

app/views/muscles/_form.html.erb
<%= form_with(model: muscle, class: "contents") do |form| %>
  <% if muscle.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(muscle.errors.count, "error") %> prohibited this muscle from being saved:</h2>

      <ul>
        <% muscle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :muscle_group_id %>
    <%= form.text_field :muscle_group_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/muscles/_muscle.html.erb
<% if action_name != "show" %>
  <tr id="<%= dom_id muscle %>" class="table-row">
    <td class="table-cell text-center border border-gray-400">
      <%= muscle.name %>
    </td>
    <td class="table-cell text-center border border-gray-400">
      <%= muscle.description %>
    </td>
    <td class="table-cell text-center border border-gray-400">
      <%= muscle.muscle_group.name %>
    </td>
    <td class="table-cell text-center border border-gray-400">
      <%= muscle.exercises.length %>
    </td>
    <td class="table-cell text-center border border-gray-400">
      <div class="flex flex-row justify-evenly">
        <%= link_to muscle do %>
          <%= render 'shared/view_icon' %>
        <% end %>
        <%= link_to edit_muscle_path(muscle), class: "border-1 border-solid rounded-sm" do %>
          <%= render 'shared/edit_icon' %>
        <% end %>
        <hr class="mt-6">
      </div>
    </td>
  </tr>
<% end %>

<% if action_name == "show" %>
  <div id="<%= dom_id muscle %>" class="border-solid rounded-md border-2 p-2 m-1">
    <p class="my-5">
      <strong class="block font-medium mb-1">Name:</strong>
      <%= muscle.name %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Description:</strong>
      <%= muscle.description %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Muscle group:</strong>
      <%= muscle.muscle_group.name %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1"># Exercises:</strong>
      <%= muscle.exercises.length %>
    </p>

    <% if action_name != "show" %>
      <%= link_to "Show this muscle", muscle, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to "Edit this muscle", edit_muscle_path(muscle), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
      <hr class="mt-6">
    <% end %>
  </div>
<% end %>

app/views/muscles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing muscle</h1>

  <%= render "form", muscle: @muscle %>

  <%= link_to "Show this muscle", @muscle, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to muscles", muscles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/muscles/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Muscles</h1>
    <%= link_to "New muscle", new_muscle_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <% if action_name == "show" %>
    <div id="muscles" class="min-w-full">
      <%= render @muscles %>
    </div>
  <%end%>
  
  <% if action_name != "show" %>
    <div class="my-2">
      <table id="muscles" class="table table-fixed w-full border border-gray-400">
        <thead class="table-header-group">
          <tr class="table-row">
            <th class="table-cell text-center px-4 py-2 text-emerald-600 border border-gray-400">Name</th>
            <th class="table-cell text-center px-4 py-2 text-emerald-600 border border-gray-400">Description</th>
            <th class="table-cell text-center px-4 py-2 text-emerald-600 border border-gray-400">Muscle Group</th>
            <th class="table-cell text-center px-4 py-2 text-emerald-600 border border-gray-400">Exercises</th>
            <th class="table-cell text-center px-4 py-2 text-emerald-600 border border-gray-400">Actions</th>
          </tr>
        </thead>
        <tbody>
          <%= render @muscles %>
        </tbody>
      </table>
    </div>
  <%end%>
</div>

app/views/muscles/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New muscle</h1>

  <%= render "form", muscle: @muscle %>

  <%= link_to "Back to muscles", muscles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/muscles/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @muscle %>

    <%= link_to "Edit this muscle", edit_muscle_path(@muscle), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= link_to "Destroy this muscle", muscle_path(@muscle), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to muscles", muscles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>